platform :ios, '8.0'

target 'flutter_hybrid’ do

    pod 'SVProgressHUD'

    flutter_application_path = 'flutter_moudle/'
    eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
